version: "3.8"
services:
    backend:
        build:
            context: ./server/Java/JavaServer
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - app-network
        depends_on:
            - db

    frontend:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app-network

    db:
        image: mariadb:10.4.32
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - "./backup_db.sql:/docker-entrypoint-initdb.d/backup_db.sql"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - db

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
